### ISSUE TITLE
失效了，之家新闻列表 广告条目 空白！

### ISSUE THREAD

**Issue by xieao100** [Yves-X/ithome-CPS-Filter#1]
![image](https://user-images.githubusercontent.com/15829332/39222923-e1af774e-4871-11e8-8690-1cb19a9ab40d.png)

**Comment by Yves-X** [comment]
1. 广泛使用的广告屏蔽规则集 EasyList China 更新了针对 IT 之家的规则，屏蔽了新闻列表内的 CPS 广告，所以 Adblock、uBlock 等扩展现在也参与了新闻列表广告过滤。

2. 受 IT 之家布局的影响，在首页直接移除广告条目会导致新闻列表错位变形。所以本脚本在首页只隐藏广告内容，保留了空白条目。EasyList China 一开始没有注意这个问题，现在也进行了修正，实现了与本脚本一样的效果。所以你看到的空白条目是插件 / 脚本在正常工作，无论是 uBlock Origin 还是本脚本都会呈现相同效果。

3. 也即，现在脚本与 uBlock Origin 的功能有重合。虽然并不会相互冲突，但本着精简的原则，仍可以卸载 / 停用其中一个。

**Comment by xieao100** [comment]
好吧 那我还是用规则吧
